# Project Name
TARGET = vca_eg

# Sources
CPP_SOURCES = vca_eg.cpp daisy_common.cpp envelope.cpp

# Library Locations
LIBDAISY_DIR = ../../../../DaisyExamples/libDaisy/
DAISYSP_DIR = ../../../../DaisyExamples/DaisySP/
# DAISYCOMMON_DIR = ../daisy_common/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

