# Project Name
TARGET = ampenv

# Sources
CPP_SOURCES = ampenv.cpp daisy_common.cpp voice.cpp

# Library Locations
LIBDAISY_DIR = ../../../../../DaisyExamples/libDaisy/
DAISYSP_DIR = ../../../../../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
